lidar_topic: /velodyne_points
imu_topic: /imu/data
lidar_type: velodyne # livox velodyne ouster
min_radius: 1.0
max_radius: 100.0
point_filter_num: 4
time_scale: 1000.0 # nclt: 0.001 other: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.0001
ba_cov: 0.000001
bg_cov: 0.000001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

# kuangye rotating vlp16
t_imu_lidar : [-0.0119, -0.00802, -0.06139]
R_imu_lidar: [ 0, 0, 1,
               0, 1, 0,
              -1, 0, 0]

pcd_save_en: true
pcd_save_interval: 20                 # how many LiDAR frames saved in each pcd file, -1: all;
pcd_save_frame: "lidar"               # "world", "imu", "lidar"