lidar_topic: /epic_points
imu_topic: /imu/data
lidar_type: hesai_xiangyin # livox velodyne ouster
min_radius: 1.0
max_radius: 200.0
point_filter_num: 4
time_scale: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false
enable_gyro_correct: false
tbb_threads: 1 # 0 auto, 1 single thread

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.0001
ba_cov: 0.000001
bg_cov: 0.000001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
init_pos_cov: 0.0001
init_vel_cov: 1.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

# xiangyin hesai 32
t_imu_lidar: [ -0.0033, 0.06357, 0.08515]
R_imu_lidar: [0.999743, 0.0152831,  -0.0167245,
              -0.0152252,  0.999878,   0.0035855,
              0.0167772,  -0.00332994,  0.999854 ]

pcd_save_en: true
pcd_save_interval: 1                 # how many LiDAR frames saved in each pcd file, -1: all;
pcd_save_frame: "lidar"               # "world", "imu", "lidar"
